alkimia_door:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
    - fin1_top_joint
    gains:
      fin1_top_joint: {p: 50000,  d: 10, i: 10000, i_clamp: 1000}
